
name: Run tests

on:
  push:
  pull_request:
    branches-ignore: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          # Python 3.4 is not available on mac and windows so it needs to to
          # be manually added to the matrix for linux.
          - python-version: 3.4
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install codecov
        python scripts/ci/install
        python scripts/ci/install-check
    - name: Run tests and checks
      run: |
        python scripts/ci/run-tests
        python scripts/ci/run-check

    - name: codecov
      run: |
        rm tests/coverage.xml
        mv tests/.coverage ./
        codecov
